### ISSUE TITLE
File permission issue on Windows

### ISSUE THREAD

**Issue by kytwb** [getferdi/internal-server#2]
Related to https://github.com/getferdi/ferdi/issues/253. 
I guess the issue comes from this line:

https://github.com/getferdi/internal-server/blob/48cb16fefe46ab66b1884f18e04c1f701a8e0c09/start.js#L32

I have never had to copy a database template like this before; isn't it possible to let the app bootstrap the database without copying this file? I am not sure what is in the template file for now and what it would take to bootstrap without, just opening the issue.

**Comment by kytwb** [comment]
If we decide to solve the permission issue using the current implementation, we should be taking a look at https://github.com/jprichardson/node-fs-extra/issues?utf8=%E2%9C%93&q=permission+windows; maybe we can manually chmod things?

**Comment by vantezzen** [comment]
Looks like this is a general problem when copying files from asar: https://stackoverflow.com/questions/56593560/why-are-files-copied-from-asar-readonly.
I now added a possible fix via 65d1468 that doesn't copy it but first reads, then writes manually as that is the suggested solution from the Stackoverflow question above.

**Comment by vantezzen** [comment]
I've done some more testing on Windows and it looks like the solution mentioned above doesn't actually solve this issue.
There is however a section in Electron's documentations about [treating ASAR files as a normal file](https://www.electronjs.org/docs/tutorial/application-packaging#treating-an-asar-archive-as-a-normal-file). I now implemented this solution and it seems to work but we'll have to see if it also works after building the application.

**Comment by PeterCxy** [comment]
@vantezzen The documentation you linked talks about how to read the asar file *itself* as a whole, for signature checking and stuff, not about accessing files from *inside* asar. The commit 24c8ea3aad5b828297686a032103d2cc4eabc373 you have added simply breaks everything:

> (node:70827) UnhandledPromiseRejectionWarning: Error: ENOTDIR: not a directory, open '/usr/lib/ferdi/resources/app.asar/internal-server/database/template.sqlite'

because now **nothing** can be read from inside the asar when you set `noAsar`.

**Comment by vantezzen** [comment]
@PeterCxy Thank you for the comment, I misunderstood the docs there, I just reverted the commit you've mentioned.
Do you know of any other way that might fix this problem instead?

**Comment by PeterCxy** [comment]
I'm not sure why the file can still be read-only when you have literally just written to the file from a byte stream, not copying it. Not sure about how these things work on Windows, but it seems very, very strange....

**Comment by kytwb** [comment]
What about making a call to `fs.chmod` with `0666` after write is successful until we grasp our heads around what is really going on? @PeterCxy do you have the ability to run the development app on a Windows machine for further debugging?

**Comment by PeterCxy** [comment]
Unfortunately I don't have a Windows machine at my hand. I commented on this issue simply because that commit broke my dev build on Linux...

**Comment by vantezzen** [comment]
8dc6b3a could have fixed the problem but we'll have to test that on the Windows Remote Desktop

**Comment by vantezzen** [comment]
This seems to be fixed with 5.5.0 now
